---
title: "MovieReviews"
author: "Krestal Joy Cabico"
date: "2024-02-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r}
library(rvest)
library(dplyr) 
library(purrr)
library(stringr)
```

```{r}
polite::use_manners(save_as = 'polite_scrape.R')

url <- 'https://www.imdb.com/title/tt15314262/?ref_=chtmvm_t_4' 

webpage <- read_html(url)

extract_review_info <- function(review_node) {
  username <- review_node %>% html_node(".display-name-link") %>% html_text()
  date <- review_node %>% html_node(".review-date") %>% html_text()
  stars <- review_node %>% html_node(".rating-other-user-rating") %>% html_text()
  review <- review_node %>% html_node(".text") %>% html_text()
 
  return(data.frame(
    title = c("The Beekeeper"),
    username = username,
    date = date,
    stars = as.numeric(stars),
    content = review
  ))
}

reviews <- webpage %>% html_nodes(".review-container") %>% map_df(extract_review_info)


for (page_num in 2:9) {
  url <- paste0("https://www.imdb.com/title/tt15314262/?ref_=chtmvm_t_4", page_num)
  webpage <- read_html(url)
  reviews <- bind_rows(reviews, webpage %>% html_nodes(".review-container") %>% map_df(extract_review_info))
}


View(head(reviews, 300))
```